#!/bin/bash

module load r-4.0.3-gcc-10.2.0-6ikej77

mkdir -p exec
mkdir -p log
rm -rf exec/* 2> /dev/null
rm -rf log/* 2> /dev/null

irace --batchmode slurm --target-runner target-runner-slurm --target-evaluator target-evaluator
