#!/bin/bash

if hash condor_submit 2>/dev/null
then

HOME=/lhome/ext/iiia021/iiia0211
export LCGENV_PATH=/cvmfs/sft.cern.ch/lcg/releases
eval "`$LCGENV_PATH/lcgenv/latest/lcgenv -p LCG_93 x86_64-slc6-gcc7-opt R`"
export R_LIBS=$R_LIBS:$HOME/R-libs
export PATH=$HOME/R-libs/irace/bin:${PATH}
rm -rf $HOME/log/irace 2> /dev/null
mkdir -p $HOME/log/irace
irace --batchmode htcondor --target-runner target-runner-htcondor --target-evaluator target-evaluator-htcondor

elif hash sbatch 2>/dev/null
then

module load r-4.0.3-gcc-10.2.0-6ikej77
rm -rf /mnt/beegfs/iiia/filippo.bistaffa/irace 2> /dev/null
mkdir -p /mnt/beegfs/iiia/filippo.bistaffa/irace
irace --batchmode slurm --target-runner target-runner-slurm --target-evaluator target-evaluator-slurm

else
echo "Unknown cluster"
fi
